jobs:
  include:
    - language: python
      python:   
      - "3.6" # Current default Python on Travis CI
      - "3.9" # Current version that Jaxon is running

      # command to install dependencies
      install:
      - pip install -r requirements.txt
      script:
      - python -v back_end_test.py

    # There is more to be written for this, this is an incomplete framework
    - language: node_js
      node_js:
      - "12" # Mentioned in the docs
      - "15" # Current version that Jaxon is running
      install:
      - npm install
      script:
      - npm start

